---
# Source: temporal/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-grafana
  namespace: argocd
  labels:
    helm.sh/chart: grafana-8.0.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "11.0.0"
    app.kubernetes.io/managed-by: Helm
data:

  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: TemporalMetrics
      type: prometheus
      url: http://test-prometheus-server
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards/default
      orgId: 1
      type: file
  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf
    mkdir -p /var/lib/grafana/dashboards/default

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/advanced-visibility-specific.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/misc-advanced-visibility-specific-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/clustermonitoring-kubernetes.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/misc-clustermonitoring-kubernetes-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/frontend-service-specific.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/misc-frontend-service-specific-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/history-service-specific.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/misc-history-service-specific-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/matching-service-specific.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/misc-matching-service-specific-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/worker-service-specific.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/misc-worker-service-specific-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/sdk/sdk-general.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/sdk-general-github.json"

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://raw.githubusercontent.com/temporalio/dashboards/helm/server/server-general.json" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "TemporalMetrics",/g' \
    > "/var/lib/grafana/dashboards/default/server-general-github.json"
