---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: tank-db
  resources:
    requests:
      storage: 10G
