apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacks
  namespace: vs-apps
  labels:
    app.kubernetes.io/name: stacks
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: stacks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stacks
    spec:
      serviceAccountName: stacks
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: stacks
          image: "ghcr.io/drewpayment/stacks:df8b9af0773eb6593d7bd6970291a1e218c10ef1"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: CMP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: CMP_CLIENT_ID
            - name: ENABLE_DRIZZLE_LOGGER
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: ENABLE_DRIZZLE_LOGGER
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_PORT
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_NAME
            - name: MYSQL_USE_SSH
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_USE_SSH
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_PORT
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: MYSQL_DB_NAME
            - name: POSTGRES_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_PORT
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_USER
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_PASSWORD
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_NAME
            - name: POSTGRES_MAX_CONNECTIONS
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_MAX_CONNECTIONS
            - name: FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: FROM_EMAIL
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: RESEND_API_KEY
            - name: ORIGIN
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: ORIGIN
