---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1a0n0xhsujvpq03fcqjm97stf6pjzeq0gfu9cvcm3zu8zpnl2y5aqyuwmjc"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1a0n0xhsujvpq03fcqjm97stf6pjzeq0gfu9cvcm3zu8zpnl2y5aqyuwmjc"
