apiVersion: v1
kind: Secret
metadata:
  name: docker-io-helm-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: registry1.docker.io/bitnamicharts
  name: bitnamicharts
  type: helm
  enableOCI: "true"
