apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.86.44
  share: /mnt/tank/appdata
volumeBindingMode: Immediate
reclaimPolicy: Delete
mountOptions:
  - hard
  - nfsvers=4.1
