apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets-store
  namespace: affine
spec:
  provider:
    doppler:
      project: talos-home-ops
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-auth
            key: dopplerToken
            namespace: external-secrets
