---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: affine-ingress
  namespace: affine
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - notes.drewpayment.com
    secretName: affine-tls
  rules:
  - host: notes.drewpayment.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: affine-server
            port:
              number: 80