

---
# PersistentVolumeClaim for uploads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-upload-pvc
  namespace: affine
  annotations: 
    # volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/nfs
    nfs.io/path: /mnt/tank/appdata/affine/upload
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: affine-storage
  resources:
    requests:
      storage: 5Gi
      
---
# PersistentVolumeClaim for config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config-pvc
  namespace: affine
  annotations: 
    # volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/nfs
    nfs.io/path: /mnt/tank/appdata/affine/config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: affine-storage
  resources:
    requests:
      storage: 1Gi