---
apiVersion: v1
kind: Service
metadata:
  name: affine-server-svc
  namespace: affine
spec:
  ports:
  - port: 3010
    protocol: TCP
    targetPort: 3010
  selector:
    app: affine-server-svc
  type: LoadBalancer
