---
apiVersion: v1
kind: Service
metadata:
  name: affine
  namespace: apps
  labels:
    app.kubernetes.io/name: affine
spec:
  type: ClusterIP
  ports:
    - port: 3010
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: affine-server-svc

