---
apiVersion: v1
kind: Service
metadata:
  name: affine-server-svc
  namespace: affine
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: affine-server-svc
  type: ClusterIP
