apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
secrets:
  - name: homepage
