apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UhtFOBNT24+krGaIvjiZWn6SvwRmADHygYqyu/xrJhpe6kIy,iv:/Ftod6LjPeMTb4WKE9Gle8u9SXf7JLD11Vup9X3ISpw=,tag:KOonhetTOCcsc58rOdXekA==,type:str]
    credentials.json: ENC[AES256_GCM,data:Mzu1JIk0EedLz+0LxDNE/rGJg+4u0cTks2jlMKxbNu4vT1ZjpiT/hhlGvYV8EU7ck0NVK0vtUC8xo0EqqyVRJj2rpNx3eYspqLn25XoieHIeD05Gr6IKSX/ZxFyOeJuWrwYS13tKVaXS6kBIMTjS30xJy6FKwVfzkLSevDWiKbJCBoih8nte8lWPAPj1Bw5Gr2J3JDRw/y3oAFy0ICIS3YYZGvBzCP/deL1dhDoggA==,iv:A1WUduxeaHxODzVIoJY95thvrxs+FhF4wbmUZCkwp7o=,tag:n6oqjVJD5k4l0rzMNn4lNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rzqv3kzkdavx5er9fjws3jjfgj895g8mx46k99jwjya8wa0he0qtrthh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUVltcHNnaUlyU0ticytJ
            cTZRQjV6US9Ock9wdUI5Wkg0NTZOUUUxS3pVCmdzYjY2QkNIWmJ5b0hVQVU5b3Qv
            UDJBbGRpUnNkRWlYWERHUExBUnNOMkUKLS0tIE1FNWlqWENvYnJBcTdGdkVhOW1t
            bTRBd2djMDBJM0pLVS9KVnNqY3h6Y28K8HOED5FwSr1BFbqeGIaQ9Q6UUzuLf7ix
            0BTc7ZVqCZUwZFslKJx2ukhPA5SCtf9hpIRSb60m0b/xvFv8fgYynQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T19:30:54Z"
    mac: ENC[AES256_GCM,data:+Y60QxE/KKGhd4WCKYLc1GGdrIaCttn8YMMXRr3l9c5va6DWsLwC16X4P34oGF19UbFFVSY3RMCE4l9XXdIicagBBppR8+yShtTaJwowe07xUJyD8l1bKjFpEqXBMrGI8XDSIjYh234coyXosLNM4hQqnZ+jsR7h9OtcWnRoDUM=,iv:TLdEm6yiyDjZbYf4zbqa4CUV5eAn4LDJLSanuKCv7sg=,tag:yRMh6YiJZ4MEpNrPbqyO1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
