---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app code-server
  namespace: code-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    controllers:
      code-server:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/code-server
              tag: 4.91.1
            env:
              TZ: America/New_York
              PUID: 911
              PGID: 911
              PROXY_DOMAIN: code.drewpayment.com
              DOCKER_MODS: linuxserver/mods:universal-git|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-terraform
              DEFAULT_WORKSPACE: /config/workspace
              # DOCKER_MODS: "linuxserver/mods:code-server-docker|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-terraform|linuxserver/mods:universal-git|linuxserver/mods:universal-tshoot|linuxserver/mods:universal-package-install"
              INSTALL_PACKAGES: "rsync|git|nginx"
              # INSTALL_PIP_PACKAGES: "apprise"
    service:
      app:
        controller: code-server
        ports:
          http:
            port: 8443
    ingress:
      app:
        className: external
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: github
          external-dns.alpha.kubernetes.io/target: "external.drewpayment.com"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: file-code
        hosts:
          - host: &host "code.drewpayment.com"
            paths:
              - path: /
                service:
                  identifier: app
                  port: 8443
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: code-server-pvc
        globalMounts:
          - subPath: "data"
            path: "/home/coder"
          - subPath: "ssh"
            path: "/home/coder/.ssh" # override secret mount perms

    # persistence:
    #   config:
    #     enabled: true
    #     type: pvc
    #     accessMode: ReadWriteOnce
    #     size: 5Gi
    #     mountPath: /config
    #     storageClass: local-path

    fullNameOverride: code-server
    podAnnotations:
      reloader.stakater.com/auto: "true"
      setGateway: "true"
