---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tank-db
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.86.44
  share: /mnt/tank/db
reclaimPolicy: Retain
volumeBindingMode: Immediate
