apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SLCFm1UtejKcniYInmVTcgncRXjPdDjDFyTfsx6TyfSQFOkPJk7z6Q==,iv:yeTq8fep5m/1yckDC+cIndbCi6UN5+Tl9rShaRbZo58=,tag:iv/tMmmY7NIfnqrW8JHAIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rzqv3kzkdavx5er9fjws3jjfgj895g8mx46k99jwjya8wa0he0qtrthh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUUI1ZjFlMEU5bFkybkk3
            TldBNmtXSFZmWXBCZ0wzMVV3UmYybGE3UkJzClpicWFCVHoxeDlJZ0d6VkY1OXkx
            S3AyZ0RDamlBenhqME05ZG5PUlkzU0kKLS0tIGIxbFg0S2c0L05ZazhIZGVSRDAy
            bWhqbnozWXRPZ0pQVUpEZVJpZHprM3cKpXi4b6pKaGOoatwX/+Czsu2tpHUXmK3e
            KivfrGB6ONUV9D9HwIfBPvsTOSGS6Ik6ugMNrsY4rdrCs5hvrlviOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T17:25:07Z"
    mac: ENC[AES256_GCM,data:bJxKu0KwYvsBKSyH7TVKjdcnUmINhNN65blLzrMROU6QE1Z6fHV90dnXng2nlzhIFhvPcOanPl99R+BAWOMjiHi7ZaZ2SR5Z22mR+0+LQ0qvJOuBquIWsnLnZZXhYBQqd/c2n+q/zm1Ye0LUIna+QcmQ7SRqXhaXvEsTugQkifE=,iv:2ej6QnY11nqf7aogKIHg8o0Aqh7gQMYi+lEzZliXl0g=,tag:GDrDCEW7ou2E8iL7hUToFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
