apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:s0KgOGMSy8sz1ctoM32T3xlenNr0kw9FjnbOnA4cwN8NSIbRk9RADQ==,iv:cEuuAL1b3seX79hUgVECS0tvDzV6ite0eujvEXbT3bY=,tag:fLYr3GAmrUY+uwnxLoFsbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rzqv3kzkdavx5er9fjws3jjfgj895g8mx46k99jwjya8wa0he0qtrthh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdDVRMDJZZk93R1RwZnR3
            OVJ3UGhCT0FxK1VtN3JySkpucjFCcG56VTNZCjdLMUtUc3EwK1dVNWIrRGVCdzl2
            U1pzRlVNdm1GZXpKbmRzL3BQL21NVTAKLS0tIHNqaTMzNnMzMkNGcXJmQ3hXZW9E
            d0FyaXRxK2ovWUQ0aVhUU05ZTmZjNjgKgbN4if2qpj8DMpTarsORiFbwkTsC948J
            xOvVQSJRFG/iFQo1fU9hZY72tJEm9UNdefwGsM5G2PkoZe/eBTBSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T23:37:53Z"
    mac: ENC[AES256_GCM,data:ziLzpLQqoAcstjZbmk9JrU/Y+Q1HFHCxCQYe9d5pWacyKz3aCU1SD2tGaKRtiQ8x/9kpJ4tArMrGDKV3xJUvtrHixnzmBrxbGIdm55LpAxU3rvGz/boCFcr5S91lXAj584puBV5OP79mrYuJ4R9Ie9xdU1z5CCuU96i0zgc368M=,iv:PtggIVSAusX8xmvs13WIM/IMvmzxbn/RTt/nFuUgDRo=,tag:DdND15J2R7KMn3lji6OkaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
