apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    external-dns.home.arpa/enabled: "true"
spec:
  ingressClassName: external
  rules:
  - host: &host 'argocd.${SECRET_DOMAIN}'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
  tls:
  - hosts:
    - *host
    secretName: argocd-server-tls # as expected by argocd-server
