apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Homepage project
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'homepage'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
