---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:latest
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
        env:
          - name: HEADLAMP_CONFIG_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: cluster-external-secrets
                key: HEADLAMP_CONFIG_OIDC_CLIENT_ID
          - name: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: cluster-external-secrets
                key: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
          - name: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
            value: "https://id.drewpayment.com/realms/id-drewpayment-com"
          - name: HEADLAMP_CONFIG_OIDC_SCOPES
            value: "email,profile"
        ports:
        - containerPort: 4466
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        'kubernetes.io/os': linux
