apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-external-secrets
  namespace: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-store
  target:
    name: cluster-external-secrets
  dataFrom:
    - find:
        name:
          regexp: ".*"
