apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: overseerr
    controllers:
      overseerr:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: docker.io/sctx/overseerr
              tag: latest
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: debug
    service:
      app:
        controller: overseerr
        ports:
          http:
            port: 5055
    persistence:
      config:
        existingClaim: appdata
        globalMounts:
          - path: /app/config/overseerr
            readOnly: false
    ingress:
      app:
        className: external
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: movie-open-check
          hajimari.io/icon: arcticons:overseerr
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host media.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
              
    fullNameOverride: overseerr
    podAnnotations:
      reloader.stakater.com/auto: 'true'
      setGateway: 'true'
