apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: homepage
