metadata:
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewpayment/talos-home-ops.git
    targetRevision: HEAD
    path: argocd/apps/homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
