apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-app
  namespace: argocd
spec:
  project: default
  source:
    chart: supabase
    repoURL: registry-1.docker.io/bitnamicharts
    path: argocd/apps/supabase/charts/supabase
    targetRevision: 4.0.3
    helm:
      releaseName: supabase
      valueFiles:
        - argocd/apps/supabase/charts/supabase/values.example.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
