apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true  # Delete resources that are no longer in Git
      selfHeal: true # Attempt to fix out-of-sync resources
  source:
    repoURL: https://github.com/drewpayment/talos-home-ops.git
    path: argocd/apps/supabase/charts
    # chart: supabase
    # targetRevision: HEAD # Or you can specify a branch or tag
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
