apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-app
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/drewpayment/talos-home-ops.git'
    path: 'argocd/apps/supabase'
    targetRevision: HEAD
    ref: values

  - repoURL: 'registry-1.docker.io/bitnamicharts'
    path: 'supabase'
    targetRevision: 4.0.5
    chart: supabase
    helm:
      valueFiles:
      - $values/argocd/apps/supabase/values.yaml

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true  # Delete resources that are no longer in Git
      selfHeal: true # Attempt to fix out-of-sync resources
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
