apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true  # Delete resources that are no longer in Git
      selfHeal: true # Attempt to fix out-of-sync resources
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: supabase
    targetRevision: 0.24.3 # Or you can specify a branch or tag
    helm:
      releaseName: supabase
      valueFiles:
      - supabase/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
