apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewpayment/talos-home-ops.git
    targetRevision: HEAD
    path: argocd/apps/supabase
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
