apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: utilities-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewpayment/talos-home-ops.git
    targetRevision: HEAD
    path: argocd/apps/utilities
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
