apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vs-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewpayment/talos-home-ops.git
    targetRevision: HEAD
    path: argocd/apps/vs-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
