---
# Source: temporal/charts/prometheus/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-prometheus-node-exporter
  namespace: argocd
  labels:
    helm.sh/chart: prometheus-node-exporter-4.36.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.8.1"
