apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
spec:
  project: default
  source:
    chart: supabase
    repoURL: https://github.com/drewpayment/talos-home-ops.git
    path: argocd/apps/supabase/charts/supabase
    targetRevision: 4.0.4
    helm:
      releaseName: supabase
      valueFiles:
      - argocd/apps/supabase/charts/supabase/values.example.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
