apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: supabase
spec:
  project: default
  source:
    chart: supabase
    repoURL: registry-1.docker.io/bitnamicharts
    path: supabase
    targetRevision: 4.0.4
    helm:
      releaseName: supabase
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
