apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: supabase
spec:
  project: default
  source:
    chart: supabase
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: HEAD
    helm:
      releaseName: supabase
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
