apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:TSX+F9OcNnbmiZpgBfr1JQgsGdOObou8BWxlc51niKCjFd8voizDS1V8sz3nP16SIEpbK4QOTN85JijXygZ19sWalb8adrLDlXdc3KPf8VKpoXWqUbMAyWYRVIsgyQ==,iv:5UtEnmjzWKcOumcTtRhPI3fCFRf8JTd5bBEUx1HsJt8=,tag:brCeyNslZzefKRD3fb4kNg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:TL3oVxwW5LfQRq8QCmxv,iv:i3RfTBt7F6y72cRvS96ALx4VtZHcgiteKHCNf5c7N+Y=,tag:QyJPAqNJp0tynBhkr2UEww==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:uYxsai729b66tb7YYUn3m1Dl7GBseQ==,iv:J1m0wlV9s7FF4DsXf3BazgRCbCURLjrpHO4QqP1ydGM=,tag:vZS14mOOIFBjN50rIZ4UJg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:axP4qxg3lGKyhAejbXSSn2Z+/wxJuMOvbiK6sudmMf0UuU+V,iv:59CYQKjuuSHXpjpRBKFWTU/GO3QpuR87wl1+owP+prg=,tag:LO/B1HoiWMeKBU/IhDcwcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rzqv3kzkdavx5er9fjws3jjfgj895g8mx46k99jwjya8wa0he0qtrthh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSXpmN01WUEhkSk1xV1BJ
            QzV3Y0tYRDRTaU5RTFF3dUR2cE4xVHRqQUJzCkc2MVh6VFBlbUlDQko5azd4d0Ri
            Y0FJMUNJU1hWazBqMlUwbUJxa1hlN0UKLS0tIHFhajFFK2NQMkRLOWlrS1Q2YzRw
            REd1ZFZVcTBIY1krQnJkdHJ2WWFsM0UKVEuCCCAv+DajmALpcNqJXQBRUYpHwLX8
            ILwTyq0M7krKuM0RspwBzkrVL/6SsYXvIQiUZNWqiPpk/sBrPBkXFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T17:25:07Z"
    mac: ENC[AES256_GCM,data:QTm8t1tOPk836pA/23a56B2/JjBH0aUl+O7qv7ALwAkP9A0ujbeMXBPYtmYVUY5Qrn59A8kY8BFX+RGFYF2wXtB2pNZogwdgfs0OPnT2tqxvwn5lo0yQjT0k1yg23a15kIJzKw20hA11UJHx2+pg/x7mIpMrS6VzJmnHqUma/r8=,iv:3MuXjLGQByJmRAPAn63uQR1yQgty44biVWF0jck3aEU=,tag:buNfb8wI+sD7pYhkzryKXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
