---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: hoarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - env:
        - name: MEILI_NO_ANALYTICS
          value: "true"
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: cluster-external-secrets
              key: MEILI_MASTER_KEY
        - name: NEXT_PUBLIC_SECRET
          valueFrom:
            secretKeyRef:
              name: cluster-external-secrets
              key: NEXT_PUBLIC_SECRET
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: cluster-external-secrets
              key: NEXTAUTH_SECRET
        envFrom:
        - configMapRef:
            name: hoarder-configuration-h4242cgbtk
        image: getmeili/meilisearch:v1.11.1
        name: meilisearch
        volumeMounts:
        - mountPath: /meili_data
          name: meilisearch
      volumes:
      - name: meilisearch
        persistentVolumeClaim:
          claimName: meilisearch-pvc
