---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tank-db
  resources:
    requests:
      storage: 1Gi
