---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hoarder-pv
  namespace: hoarder
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hoarder-storage
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/hoarder

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoarder-pvc
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hoarder-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: hoarder-pv
