apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: external-secrets-store
spec:
  provider:
    doppler:
      project: talos-home-ops
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken


