apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-registry-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: external-secrets-store  # reuse your existing secret store
  target:
    name: github-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: GH_PACKAGES_PULL_SECRET  # your Doppler secret name
