apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-registry-secret
spec:
  namespaceSelector:
    matchLabels:
      # Add this label to any namespace that needs the secret
      needs-github-secret: "true"
  externalSecretSpec:
    secretStoreRef:
      kind: SecretStore
      name: external-secrets-store
    target:
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: GH_PACKAGES_PULL_SECRET
