---
# Source: temporal/charts/prometheus/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v2.53.0
    helm.sh/chart: prometheus-25.22.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus
  name: test-prometheus-server
subjects:
  - kind: ServiceAccount
    name: test-prometheus-server
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-prometheus-server
