---
# Source: temporal/charts/prometheus/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v2.53.0
    helm.sh/chart: prometheus-25.22.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus
  name: test-prometheus-server
  namespace: argocd
  annotations:
    {}
