---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: code-server-storage
  namespace: code-server
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.86.44
  share: /mnt/tank/appdata
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: code-server-storage
  resources:
    requests:
      storage: 60G
