---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: tank-db
  resources:
    requests:
      storage: 60G
