apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:/MEDyawtEqy0lcss13s2tOgu7v5V2ZDU,iv:dgWNMA2R42/tBFQ2bxmqrWRRnulUbJRZQlV6IdU9shA=,tag:pGGD0p5VKzU28KbrwtcdaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0n0xhsujvpq03fcqjm97stf6pjzeq0gfu9cvcm3zu8zpnl2y5aqyuwmjc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYm1FeHNoVUhQN1J6MHk4
            SHFwaThKVWlCNFEvSktGWTFIZm1xam9RcjM0CnFDK1J6QStqa0FKb244MzRHdDFQ
            U2xRZDV5cFI3U25KalY4ZjJsU3h3OVEKLS0tIENzbGZ1QlFYYU1RQVU2QWhUbFdE
            UE9HYjhWdHh1aCtuSkxvYWNLUlIwalUK8cZy9Q+MEUjc+FFBT31oF8ysFWjZVfey
            wmeH0SnIQHzPwkdvqRbn6BHQsFZYCOr3OyVRb3AyiiUPkbsRxnsBqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T16:20:13Z"
    mac: ENC[AES256_GCM,data:x53EAMWFSI8kQbf0+Zv6bFZ+xxmf5hnWuebybOMSz/qXTiLel3B0quK250kQGklkne3syP9p0WTi9QHNPaAZEEqXrDspMebmRuTxt/rCep6ikOxFBKg7Gt23oqW3GI/GyRlAp7DelY1iY3dpDs1x17SV11oHdvoGTadzJX1pjlk=,iv:HGuppNVVumi7MmuJCfZ6B44tovxbnYSsAvh+rSzipi8=,tag:OV5ip19ITAzJzIEZ/4ydCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
