apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ySMTgbFDdWGYAdUrrN4+4QT08H796O1WbMfnAYUEQs3wOhAOUBk+/A==,iv:1L4n/EarNIrUYqsQ9T0Pt48wThL+vtdPOoLtCDRPCBo=,tag:PFSE/bBboGdgBAu2KGyePg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rzqv3kzkdavx5er9fjws3jjfgj895g8mx46k99jwjya8wa0he0qtrthh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YjdPZGFxckMvRXNHOCt6
            S3FkSHM4VE40WStCc3ExUDd5eUZZb1pEWENNCkFLRm9zazJ5ZGFWVmJmLzdoV2w1
            UHhZRDJZOURYM2pjNHk4ZDRlRVNhQU0KLS0tIHE0UlNOZzVKRGsveUx4RzByRVdI
            TlJBNkVKY0F4SEo1bXJXZE93YU1xeUkKjMWJ7Nvatm5vaSoyTi9zf+4nsRiJgyk6
            N4dS7UokARyMbMsGPXuXy5VPKS2EvTZWb0w81BOQ19mb3p7/xutfkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T04:02:44Z"
    mac: ENC[AES256_GCM,data:0CTB/wL17aQ+9LdNgwJOZsdef3frfh+F16d7nSDAZWLaRqpM+jEzbYiUuxDfrfExVvBdBkeNv5LVRvezhog5wQtS2QkWa7rTzIlEUMWCpYzMrkAwsX2U4TxB+k9hBHcfQHHDWwGGEeKTbkq1Z0R18FW/qsK2KV/WKgEq2gyanpQ=,iv:OLIlyjoLXIREP0Tc2FYr22BZBdrWEvyRNBN5tu95T5Q=,tag:WD32OhFoHNx+6gvwPXybCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
