apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_PROXY_HEADERS
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KC_PROXY_HEADERS
            - name: KC_HTTP_ENABLED
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KC_HTTP_ENABLED
            - name: KC_HEALTH_ENABLED
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KC_HEALTH_ENABLED
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
