apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          args: ["start"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KEYCLOAK_ADMIN
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_PROXY_HEADERS
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KC_PROXY_HEADERS
            - name: KC_HTTP_ENABLED
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KC_HTTP_ENABLED
            - name: KC_HEALTH_ENABLED
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: KC_HEALTH_ENABLED
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_HOST
            - name: KC_DB_URL_PORT
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_PORT
            - name: KC_DB_POOL_MAX_SIZE
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_MAX_CONNECTIONS
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-external-secrets
                  key: POSTGRES_DB_PASSWORD
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
